[package]
name = "zmsg"
version = "0.1.0"
authors = ["Pancy <pancy@firma.org>"]
edition = "2018"

[[bin]]
bench = false
path = "src/main.rs"
name = "zmsg"

[dependencies]
console = "0.14"
anyhow = "1.0"
structopt = "0.3"
hex = "0.4.3"


